### ISSUE TITLE
Command Injection on FS Manager

### ISSUE THREAD

**Issue by CanNuhlar** [linux-remote/linux-remote#3]
There is command injection vulnerability on FS Manager's directory input. You may test it by typing below command into the input. 
> /boot\\" | cat /etc/passwd > /home/guest/testvuln \

I don't know if this project should be secure by design but considering there is no terminal emulator, I'm assuming this is not the intended behavior here.

**Comment by hezedu** [comment]
Thank you for this issue.
In fact，The API to read a folder using FS Manager is  wrap of the `ls` command. 
I don't use the fs API of NodeJS, because `ls` can get whether the file has an [ACL](https://wiki.archlinux.org/index.php/Access_Control_Lists)(the permission last `+`) and NodeJS's `fs.stat` can't.
Next, I decided to switch back to using the NodeJS [fs](https://nodejs.org/api/fs.html) API.  All results will reach expectations.

**Comment by hezedu** [comment]
First, I adjusted the security policy in the 1.1.5 version. linux-remote/server@0c92a18
All API must has X-Requested-With:XMLHttpRequest header. If you open directly in the browser, you will get a HTTP 400 error. This will prevent the injection or attack from outside。

**Comment by hezedu** [comment]
In the end, I still didn't use NodeJS' FS.  Because I found that I can't avoid use Command in other places.
 In version 1.3.0 this bug is fixed by string escape.
Thank again.
